<?php

declare(strict_types=1);

namespace App\Enums;

enum ApiErrorCode: string
{
    case LICENSE_REVOKED = 'LICENSE_REVOKED';
    case DOMAIN_MISMATCH = 'DOMAIN_MISMATCH';
    case PURCHASE_INVALID = 'PURCHASE_INVALID';
    case RATE_LIMITED = 'RATE_LIMITED';
    case ENVATO_UNAVAILABLE = 'ENVATO_UNAVAILABLE';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case TWO_FACTOR_REQUIRED = 'TWO_FACTOR_REQUIRED';
    case TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID';
    case FORBIDDEN = 'FORBIDDEN';
    case NOT_FOUND = 'NOT_FOUND';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
}
